{% set name = "ZODB" %}
{% set version = "6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: 2da749cf21c709058b2957bb1bc3d3a5d6e86b456246cb48acb5197173367c9f

build:
  noarch: python
  entry_points:
    - fsdump=ZODB.FileStorage.fsdump:main
    - fsoids=ZODB.scripts.fsoids:main
    - fsrefs=ZODB.scripts.fsrefs:main
    - fstail=ZODB.scripts.fstail:Main
    - repozo=ZODB.scripts.repozo:main

  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - setuptools
    - persistent >=4.2.0
    - btrees >=4.2.0
    - zconfig
    - transaction >=2.0.3
    - six
    - zc.lockfile
    - zope.interface
    - zodbpickle >=0.6.0

test:
  imports:
    - ZODB
    - ZODB.FileStorage
    - ZODB.scripts
    - ZODB.scripts.tests
    - ZODB.tests

  commands:
    # - fsdump --help  # no support for --help
    # - fsoids --help  # no support for --help
    # - fsrefs --help  # no support for --help
    # - fstail --help  # no support for --help
    - repozo --help
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://www.zodb.org/
  license_file: LICENSE.txt
  license: ZPL-2.1
  license_family: OTHER
  summary: ZODB, a Python object-oriented database
  dev_url: https://github.com/zopefoundation/ZODB
  doc_url: http://www.zodb.org/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
